repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.1.0
    hooks:
      - id: cargo-sort
        args: [--workspace]
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.17.0
    hooks:
      - id: cargo-deny
        args: ["--all-features", "check"]
