repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        pass_filenames: false
      - id: cargo-check
        args: ["--features", "server"]
        pass_filenames: false
      - id: clippy
        args: ["--features", "server"]
        pass_filenames: false
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v2.1.3
    hooks:
      - id: cargo-sort
        args: ["--workspace"]
        pass_filenames: false
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.19.4
    hooks:
      - id: cargo-deny
        args: ["check", "all"]
        pass_filenames: false
