[package]
name = "harail"
version = "0.1.0"
authors = ["Yuval Deutscher"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
csv = "1.1.3"
priority-queue = "1.0.0"
clap = "2.33.1" 
