[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-musl",
    "aarch64-pc-windows-msvc",
]

[dist.github-custom-runners]
global = "ubuntu-24.04"

[dist.github-custom-runners.aarch64-pc-windows-msvc]
# https://github.com/axodotdev/cargo-dist/blob/c8ba950c63f9c38c77782912ec6cdb6807bd0fbd/cargo-dist/src/backend/ci/github.rs#L678-L688
runner = "ubuntu-24.04"
host = "x86_64-unknown-linux-gnu"
container = { image = "messense/cargo-xwin", host = "x86_64-unknown-linux-musl", package_manager = "apt" }

[dist.github-custom-runners.aarch64-unknown-linux-musl]
runner = "ubuntu-24.04"
