services:
  harail:
    image: ghcr.io/hadeutscher/harail
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - db-data:/db
    command: /db/harail.db

volumes:
  db-data:
