[package]
name = "harail_server"
version = "0.1.0"
authors = ["Yuval Deutscher"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harail = { path = "../lib/" }
bincode = "1.3.1"
chrono = "0.4"
clap = "2.33.1"
json = "0.12.4"
tokio = "0.2.22"
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
